platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'bookkeeping' do
    pod 'pop', '1.0.12'
    pod 'SDWebImage', '4.4.3'
    pod 'Masonry', '1.1.0'
    pod 'MJExtension', '3.0.15'
    pod 'AFNetworking', '4.0.1'
    pod 'JGProgressHUD', '2.0.3'
    pod 'SDCycleScrollView', '1.75'
    pod 'ReactiveObjC', '3.1.0'
    pod 'MJRefresh', '3.1.15.7'
    pod 'MGSwipeTableCell', '1.6.8'
    pod 'BRPickerView', '2.9.1'
    pod 'Texture', '3.1.0'
    pod 'YYText', '1.0.7'
    pod 'YYImage', '1.0.4'
    pod 'KMNavigationBarTransition', '1.1.5'
    pod 'Bugly'
    pod 'HBDNavigationBar', '~> 1.9.5'
    pod 'ZLPhotoBrowser'
end

target 'BookMonth' do
  pod 'MJExtension', '3.0.15'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      # 添加以下设置来解决 pop 库的问题
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      # 确保支持的架构正确
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end 
